### ISSUE TITLE
Le logo de l'université {ul_p} devrait être dans le dossier figure donc {figure/ul_p} 

### ISSUE THREAD

**Issue by Lowstack** [clessn/memoire-ulaval#21]
https://github.com/clessn/memoire-ulaval/blob/c14bee00811442df1b1dbd99e82551ffe6c978f6/index/ulaval.cls#L323

**Comment by judith-bourque** [comment]
@lowstack Merci pour avoir signalé ce bug :smiley:

Je ne suis pas en mesure de reproduire ce bug sur mon ordinateur Mac. Le gabarit fonctionne pour moi autant avec `{ul_p}` et `{figure/ul_p}` à la ligne indiquée. J'utilise une version intégrale de LaTeX (et non TinyTex) et mes packages R sont à jour.

Afin d'éliminer certaines sources possibles du bug, voici ce que vous pouvez essayer:
1. Mettre à jour les packages suivants:
```
install.packages("rmarkdown"))

if (!require("remotes")) 
  install.packages("remotes", repos = "https://cran.rstudio.org")
remotes::install_github("rstudio/bookdown")
remotes::install_github("ismayc/thesisdown")
```
2. Installer une version intégrale de LaTeX
3. Cloner un modèle vide de ce repository et renderer `index/index.Rmd`

Si le problème persiste, merci de spécifier si vous êtes sur Mac ou PC et la version de LaTeX utilisée.

**Comment by judith-bourque** [comment]
En fait, vu que ça ne fait pas de différence de mon côté si c'est {ul_p} ou {figure/ul_p}, j'applique la modification.

@lowstack Ce serait tout de même bien de savoir si t'es sur Mac/PC et la version de LaTex utilisée (TinyTex ou intégrale quelconque). Ça pourrait nous aider à résoudre #3 #4 😄

**Comment by Lowstack** [comment]
@judith-bourque, j'ai essayé de le compiler avec MiKTeX sur mon PC windows 10 et ça ne fonctionnait pas. J'ai aussi essayé avec Linux et TinyTeX sans succès.  Par contre, sur MacOS avec MacTeX ça fonctionnait. 

Avec la modification, je suis capable de le compiler sur tous mes ordinateurs.

**Comment by judith-bourque** [comment]
@Lowstack Super, merci!
